services:
  noscopealert-rabbitmq:
    container_name: noscopealert-rabbitmq
    image: noscopealert-rabbitmq
    hostname: noscopealert-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    build: ./RabbitMQ
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  noscopealert-updategamecodes:
    container_name: noscopealert-updategamecodes
    image: noscopealert-updategamecodes
    hostname: noscopealert-updategamecodes
    build: ./UpdateGameCodes
    depends_on: 
      noscopealert-rabbitmq:
        condition: service_healthy
